appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZWKlu6HMi+dr+IycZs4PheWAVyDK8GHl1PPkmLV95auIa1UL/Vf3qSR5RDa7fkJs5OfmfEEKPmyCbnPaVT012CHie8Y/aXtC3j/sFfIpVN2xCdmbax1GnXfpVbmY6whmR0720FErOpEIShhY7eSUd4ry6dCmTHtxBZGkr0m8iWJTYRHtDum53y345LDuQqR2Dv11lm8kacYjrHIMZsPSG2f03+YfIBHDABfPxG9zwwZe/AX3ZndZ5I7cXuLqOiBppDxTQ5HuLmhaBuClzzIpL0SydVFgXjDO80TpxCGaPkLPK+y6XbisufsKul11oA++Cv+Q44WdpWfVpo56CeU54W7ESEHOdkTmzEB3NcnDcPAlhjUebmGdCTboyYeRdEoXbREVxCzqRoEzRbvjELPAA8gq6/3RZ+N6O+zrT/2w3l6bQDctLObsHg1/87MKRq1YH4k7Vx4QSkZzEGqw+qbKLvkvfbuxoQARCE+mrpJhkeYW0Swpyeld7BbqEdm3FhmthyX1guvs6dGnT7i6XK0/fWrwb6ZkCOMfoeqNP9hF64lyt4JQnhizqnIFZyx0Sz8YKePOlBOGoFvvA9WjoOYjWJgBhYrxbJYiHWMBRaAsgJ+ofKkD37JSgPqEKBIXImeC2TfTyAMPdVx+sZ9NpU+M2zXZJcEvxL2cvgZvntOuRU8=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: false
